# DynamoDB Configuration
# dynamodb.table-name=hermes-notifications
dynamodb.event-store-table-name=hermes-event-store
# # DynamoDB Configuration - Local
# quarkus.dynamodb.devservices.enabled=false
# quarkus.dynamodb.endpoint-override=http://localhost:5678
# quarkus.dynamodb.aws.region=us-east-1
# quarkus.dynamodb.aws.credentials.type=static
# quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test
# quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test
# MongoDB Configuration
quarkus.mongodb.connection-string=mongodb://n8n:n8n@10.7.12.247:27017/?authSource=admin
quarkus.mongodb.database=hermes-dev
# Kafka Configuration
mp.messaging.outgoing.hermes-domain-events.connector=smallrye-kafka
mp.messaging.outgoing.hermes-domain-events.topic=hermes.notification.created
mp.messaging.incoming.hermes-notification-created.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.outgoing.hermes-domain-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.hermes-notification-created.connector=smallrye-kafka
mp.messaging.incoming.hermes-notification-created.topic=hermes.notification.created
mp.messaging.incoming.hermes-notification-created.auto.offset.reset=earliest
mp.messaging.incoming.hermes-notification-created.failure-strategy=dead-letter-queue
# OpenAPI/Swagger Configuration
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
mp.openapi.extensions.smallrye.info.title=Hermes Notification API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API de notifica��es do Hermes
mp.openapi.extensions.smallrye.info.contact.email=contato@olympus.com.br
mp.openapi.extensions.smallrye.info.contact.name=Olympus Team
mp.openapi.extensions.smallrye.info.license.name=Apache 2.0
mp.openapi.extensions.smallrye.info.license.url=https://www.apache.org/licenses/LICENSE-2.0.html
