# DynamoDB Configuration
dynamodb.table-name=hermes-notifications
dynamodb.event-store-table-name=hermes-event-store
# quarkus.dynamodb.endpoint-override=http://localhost:4566
# quarkus.dynamodb.aws.region=eu-central-1
# quarkus.dynamodb.aws.credentials.type=static
# quarkus.dynamodb.aws.credentials.static-provider.access-key-id=test-key
# quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=test-secret
# OpenAPI/Swagger Configuration
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
mp.openapi.extensions.smallrye.info.title=Hermes Notification API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API de notifica��es do Hermes
mp.openapi.extensions.smallrye.info.contact.email=contato@olympus.com.br
mp.openapi.extensions.smallrye.info.contact.name=Olympus Team
mp.openapi.extensions.smallrye.info.license.name=Apache 2.0
mp.openapi.extensions.smallrye.info.license.url=https://www.apache.org/licenses/LICENSE-2.0.html
